Repository fossology/atarashi, pull requests merged in 2021-01, with the labels that each got.

#78 feat(tfidf): Speed and match improvement
  atarashi/agents/tfidf.py
  atarashi/evaluator/evaluator.py
Labels: Need review, enhancement, need test

#80 fix(FileNotFoundError): Display proper error message for fileNotFoundError
  atarashi/atarashii.py
Labels: ready

#81 feat(nirjas): Update interface with Nirjas 0.0.5
  atarashi/libs/commentPreprocessor.py
  pyproject.toml
  requirements.txt
  setup.py
Labels: Need review, need test
